#!/usr/bin/env bash
# migrate-to-rules-root.sh
#
# Consolidate the repo onto the SPEC §2.1 rules-root layout, in one
# history-preserving pass against current main. Governing content goes under
# rules/, the resolver under lib/, non-governing material under _references/,
# resolver-embedded rationale under docs/, and resolver output under generated/.
# schema/ STAYS at root (its $id URLs bake in .../schema/<name>.schema.json).
#
# Deterministic parts only (moves + path repoints + fixture mirroring). The
# describing-prose edits (SPEC.md §2.1/§2.3, README, ADR, BACKLOG) and the
# pyproject [tool.pyright] extraPaths insert are applied separately by hand,
# and the id index is REGENERATED by the resolver (not sed-rewritten):
#
#   python lib/resolver/resolve.py --all --validate-only   # rewrites lib/resolver/index.json
#
# Portable (GNU sed). Idempotent: every git mv is guarded; seds are no-ops once
# applied. Run from a clean tree at the repo root.
set -euo pipefail
cd "$(git rev-parse --show-toplevel)"
[ -z "$(git status --porcelain)" ] || { echo "error: working tree not clean" >&2; exit 1; }

mv_if() { if [ -e "$1" ] && [ ! -e "$2" ]; then mkdir -p "$(dirname "$2")"; git mv "$1" "$2"; fi; }

echo "== Phase 1: resolver/ -> lib/resolver/ (must precede all lib/ seds) =="
mkdir -p lib
mv_if resolver lib/resolver

echo "== Phase 2: base/docs/ -> docs/ (merge into existing root docs/) =="
for f in harmonize register-lock security-messages terminology; do
  mv_if "base/docs/$f.md" "docs/$f.md"
done
[ -d base ] && [ -z "$(ls -A base 2>/dev/null)" ] && rmdir base || true

echo "== Phase 3: governing source -> rules/ =="
mkdir -p rules
mv_if base.yaml      rules/base.yaml
mv_if baselines.yaml rules/baselines.yaml
mv_if locales        rules/locales
mv_if retrospectives rules/retrospectives
mv_if _archive       rules/_archive

echo "== Phase 4: non-governing material -> _references/ =="
mkdir -p _references
for d in reviews local-guides en-translation-docs authoring; do mv_if "$d" "_references/$d"; done
mv_if recommended-next-25-languages.md _references/recommended-next-25-languages.md
mv_if RECOVERY-PLAN.md                 _references/RECOVERY-PLAN.md
mv_if P1-3-PLAN.md                     _references/P1-3-PLAN.md

echo "== Phase 5: resolver->lib structural depth + sys.path =="
# REPO_ROOT climbs one extra level now that the modules live under lib/resolver/.
# Keyed on 'REPO_ROOT =' so resolve.py:42's package-path insert (which correctly
# resolves to lib/) is left untouched.
sed -i 's#REPO_ROOT = Path(__file__).resolve().parent.parent$#REPO_ROOT = Path(__file__).resolve().parent.parent.parent#' \
  lib/resolver/resolve.py lib/resolver/retro_lifecycle.py \
  lib/resolver/review_manifest.py lib/resolver/archive_firewall.py bin/mint-id
# Imports resolve against lib/ (the package parent), not the repo root.
sed -i 's#sys.path.insert(0, str(REPO_ROOT))#sys.path.insert(0, str(REPO_ROOT / "lib"))#' \
  lib/resolver/retro_lifecycle.py lib/resolver/review_manifest.py bin/mint-id
sed -i 's#REPO_ROOT / "resolver" / "index.json"#REPO_ROOT / "lib" / "resolver" / "index.json"#' \
  bin/mint-id

echo "== Phase 6: resolve.py path defaults + base/docs rationale ref =="
sed -i \
  -e 's#        default="locales",#        default="rules/locales",#' \
  -e 's#        default="base.yaml",#        default="rules/base.yaml",#' \
  -e 's#        default="retrospectives",#        default="rules/retrospectives",#' \
  -e 's#        default="resolver/index.json",#        default="lib/resolver/index.json",#' \
  -e 's#root / "base" / "docs"#root / "docs"#' \
  lib/resolver/resolve.py

echo "== Phase 7: gate REPO_ROOT defaults (reviews -> _references, retros -> rules) =="
sed -i 's#REPO_ROOT / "retrospectives"#REPO_ROOT / "rules" / "retrospectives"#g' \
  lib/resolver/retro_lifecycle.py lib/resolver/review_manifest.py
sed -i 's#REPO_ROOT / "reviews"#REPO_ROOT / "_references" / "reviews"#' \
  lib/resolver/review_manifest.py

echo "== Phase 8: archive firewall gated trees =="
sed -i 's#("_archive/", "retrospectives/_archive/")#("rules/_archive/", "rules/retrospectives/_archive/")#' \
  lib/resolver/archive_firewall.py

echo "== Phase 9: bin/lint-register register path =="
sed -i 's#/locales/${LOCALE}/register.yaml#/rules/locales/${LOCALE}/register.yaml#' bin/lint-register

echo "== Phase 10: workflows =="
sed -i 's#python resolver/#python lib/resolver/#g' \
  .github/workflows/archive-firewall.yml .github/workflows/schema-validation.yml \
  .github/workflows/python-qc.yml
sed -i \
  -e 's#for f in locales/\*/register.yaml#for f in rules/locales/*/register.yaml#' \
  -e 's#for d in locales/\*/#for d in rules/locales/*/#' \
  .github/workflows/lint-register.yml
# Live workflow draft consumed by tests/validate-register-workflow.sh + app-repo CI.
sed -i \
  -e 's#"\$rules"/locales/\*/#"$rules"/rules/locales/*/#' \
  -e 's#\.translation-rules/locales/#.translation-rules/rules/locales/#' \
  .github/ISSUE_DRAFTS/p1-4b-validate-register.workflow.yml

echo "== Phase 11: rules/base.yaml internal refs =="
sed -i \
  -e 's#base/docs/#docs/#g' \
  -e 's#source: local-guides/#source: _references/local-guides/#' \
  rules/base.yaml

echo "== Phase 12: rules/_archive/README.md resolver path =="
sed -i 's#resolver/archive_firewall.py#lib/resolver/archive_firewall.py#' rules/_archive/README.md

echo "== Phase 13: resolver lint-docs fixtures mirror base/docs -> docs =="
for fx in lint-docs-bare-token lint-docs-mention-only lint-docs-unclosed-fence; do
  mv_if "tests/resolver/fixtures/$fx/base/docs/register-lock.md" \
        "tests/resolver/fixtures/$fx/docs/register-lock.md"
  [ -d "tests/resolver/fixtures/$fx/base/docs" ] && rmdir "tests/resolver/fixtures/$fx/base/docs" "tests/resolver/fixtures/$fx/base" 2>/dev/null || true
done
sed -i 's#base/docs/#docs/#' \
  tests/resolver/fixtures/lint-docs-bare-token/base.yaml \
  tests/resolver/fixtures/lint-docs-mention-only/base.yaml \
  tests/resolver/fixtures/lint-docs-unclosed-fence/base.yaml \
  tests/resolver/fixtures/lint-docs-dangling/base.yaml

echo "== Phase 14: archive_firewall test — repoint gated-tree input cases =="
# Bounded to the promotion-check block only (between the two section-comment
# markers). The -z parser round-trip cases below pair NUL-prefixed inputs with
# quote-anchored expected tuples, so a global rewrite would desync them; they
# must stay verbatim. Quote-anchoring also spares the _archived/ and
# tests/_archive/ lookalikes, which must remain UNGATED.
sed -i '/--- promotion check/,/--- -z record parser/ {
  s#"_archive/#"rules/_archive/#g
  s#retrospectives/#rules/retrospectives/#g
  s#base/docs/#docs/#g
  s#"locales/de/#"rules/locales/de/#g
  s#"resolver/resolve.py#"lib/resolver/resolve.py#g
}' tests/archive_firewall/run.py

echo "== Phase 15: test runners import the resolver package from lib/ =="
sed -i 's#sys.path.insert(0, str(REPO_ROOT))#sys.path.insert(0, str(REPO_ROOT / "lib"))#' \
  tests/resolver/run.py tests/inheritance/run.py tests/archive_firewall/run.py \
  tests/retro_lifecycle/run.py tests/review_manifest/run.py

echo
echo "== deterministic moves + repoints complete. Remaining by hand: =="
echo "  - pyproject.toml: ruff extend-exclude += _references; pyright include lib/resolver + extraPaths=[lib]"
echo "  - resolve.py --emit-dir default '.' -> 'generated'; add /generated/ to .gitignore"
echo "  - SPEC.md §2.1/§2.3, README.md, docs/ prose path edits (app-repo paths unchanged)"
echo "  - regenerate index:  python lib/resolver/resolve.py --all --validate-only"
echo "  - then run the full gate suite (tests/*/run.py + resolve --all --lint --validate-only + ruff + pyright)"
